
CREATE TABLE IF NOT EXISTS version_privileged_user(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" VARCHAR(64) UNIQUE,
    "password" VARCHAR(128),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT version_privileged_username_uniqueness UNIQUE ("username")
);

CREATE TABLE IF NOT EXISTS version_software(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(32),
    "display" VARCHAR(64),
    "token" VARCHAR(255),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT version_software_name_uniqueness UNIQUE ("name")
);

CREATE TABLE IF NOT EXISTS version_version(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "software_id" BIGINT REFERENCES version_software(id) ON DELETE CASCADE,
    "version" VARCHAR(16),
    "build" INT,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT version_software_version_uniqueness UNIQUE ("software_id", "version")
);

